export enum EClassesAction {
  LIST_CLASSES = 'LIST_CLASSES',
  UPDATE_LIST = 'UPDATE_LIST',
  ADD_CLASS = 'ADD_CLASS',
  SET_CLASS = 'SET_CLASS',
  DELETE_CLASS = 'DELETE_CLASS',
  UPDATE_CLASS = 'UPDATE_CLASS',
  SET_UPDATE_CLASS = 'SET_UPDATE_CLASS',
  GET_CLASS_DETAIL = 'GET_CLASS_DETAIL',
  SET_CLASS_DETAIL = 'SET_CLASS_DETAIL',
  SET_SUBJECT_CLASS_DETAIL = 'SET_SUBJECT_CLASS_DETAIL',
  REMOVE_SUBJECT_CLASS_DETAIL = 'REMOVE_SUBJECT_CLASS_DETAIL',
  SET_UPDATE_SUBJECT = 'SET_UPDATE_SUBJECT'
}
