export enum ECommonActions {
  SET_LOADING = 'SET_LOADING',
  SET_NOTIFICATION = 'SET_NOTIFICATION',
  SET_THEME = 'SET_THEME',
  UPLOAD = 'UPLOAD',
  GET_LIST_UPLOAD = 'GET_LIST_UPLOAD',
  SET_LIST_UPLOAD = 'SET_LIST_UPLOAD',
  SET_ITEM_UPLOAD = 'SET_ITEM_UPLOAD',
  DELETE_IMAGE = 'DELETE_IMAGE'
}
