export const ERROR_TYPE = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ERR_INTERNET_DISCONNECTED: 'ERR_INTERNET_DISCONNECTED',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  uncaught: 700,
  UNAUTHENTICATED: 401,
  BAD_REQUEST: 'BAD_REQUEST',
  PHONE_EXISTS: 'PHONE_EXISTS',
  EMAIL_EXISTS: 'EMAIL_EXISTS'
}
