export enum ESubjectActions {
  ADD_SUBJECT = 'ADD_SUBJECT',
  DELETE_SUBJECT = 'DELETE_SUBJECT',
  UPDATE_SUBJECT = 'UPDATE_SUBJECT',
  GET_SUBJECT_DETAIL = 'GET_SUBJECT_DETAIL',
  SET_SUBJECT_DETAIL = 'SET_SUBJECT_DETAIL',
  SET_CHAPTER_SUBJECT_DETAIL = 'SET_CHAPTER_SUBJECT_DETAIL'
}
