export enum EUserActions {
  USERS_LIST = 'USERS_LIST',
  UPDATE_USERS_LIST = 'UPDATE_USERS_LIST',
  GET_USER_BY_ID = 'GET_USER_BY_ID',
  UPDATE_USER_DETAIL = 'UPDATE_USER_DETAIL',
  UPDATE_USER_BY_ID = 'UPDATE_USER_BY_ID'
}
